### ISSUE TITLE
how load local .judo file?

### ISSUE THREAD

**Issue by hxxyyangyong** [judoapp/judo-ios#1]
I create a  xxx.judo
How load local .judo file?

**Comment by orospakr** [comment]
Hi @hxxyyangyong ,

The Judo SDK does not load `.judo` Experience files directly. Instead, you upload them into our Web app. Then, they are synced to the SDK that you install in your app.  When you set up the SDK, you configure it with an API key for our web API.

The benefit to this arrangement is to enable immediate updates to Judo-powered content with no app updates through the Apple App Store or Google Play required.

While this is a paid product, you can try it out to learn how it works by signing up for an account at: https://www.judo.app/signup
