### ISSUE TITLE
DeepLinks and actions handling

### ISSUE THREAD

**Issue by kalonizator** [judoapp/judo-ios#2]
I did not find how to handle actions on Judo Controllers. Do they work only with each other, but we cannot handle their actions ?  They will handle DeepLinks only inside their flow ? Did I understand right ?

**Comment by orospakr** [comment]
Hi @kalonizator ,

I'm afraid I need a little more clarity on your question. What do you mean by an Action here? Do you mean a Judo Action, like you can add to a layer in the Editor?
